global:
  mtls:
    enabled: false
  proxy:
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
  defaultResources:
    requests:
      cpu: 10m
      memory: 128Mi

grafana:
  enabled: false

prometheus:
  enabled: true

tracing:
  enabled: false

servicegraph:
  enabled: false

certmanager:
  enabled: true

kiali:
  enabled: true

pilot:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
